'use strict';
const $=id=>document.getElementById(id),KEY='nogami-okonomi-bingo-v1',C=BingoCore;
let state=C.create(),selected=null,storageBlocked=false;
try{const raw=localStorage.getItem(KEY);if(raw)state=C.restore(JSON.parse(raw));}catch(e){storageBlocked=true;$('save-status').textContent='保存データを読み込めませんでした。保存する前にブラウザ設定を確認してください。';}
function save(manual=false){if(storageBlocked&&!manual)return;try{localStorage.setItem(KEY,JSON.stringify(state));storageBlocked=false;$('save-status').textContent='このブラウザに保存済み';}catch(e){$('save-status').textContent='保存できません。ブラウザの保存設定・空き容量を確認してください。';}}
for(const id of ['rows','cols'])for(let n=3;n<=C.MAX;n++)$(id).add(new Option(n,n));
function render(){const editing=state.mode==='edit';$('title').value=state.title;$('title').disabled=!editing;$('rows').value=state.rows;$('cols').value=state.cols;$('sizes').disabled=!editing;$('free-settings').disabled=!editing;$('free').checked=state.free;$('free-position').replaceChildren();for(let r=0;r<state.rows;r++)for(let c=0;c<state.cols;c++)$('free-position').add(new Option(`${r+1}行・${c+1}列`,`${r},${c}`));$('free-position').value=state.freeAt.join(',');$('free-position').disabled=!editing||!state.free;
document.querySelectorAll('[data-size]').forEach(b=>b.setAttribute('aria-pressed',String(state.rows===Number(b.dataset.size)&&state.cols===Number(b.dataset.size))));$('edit').setAttribute('aria-pressed',String(editing));$('play').setAttribute('aria-pressed',String(!editing));$('card-title').textContent=state.title||'マイビンゴ';$('mode-label').textContent=editing?'編集モード':'プレイモード';$('hint').textContent=editing?'マスを押して文字を入力してください。':'マスを押してチェック。もう一度押すと解除できます。';
const lines=C.lines(state),winning=new Set(lines.flat().map(p=>p.join(',')));$('result').textContent=lines.length?`BINGO！ ${lines.length}列成立`:'ビンゴ '+lines.length+'列';$('result').classList.toggle('bingo',lines.length>0);$('board').style.setProperty('--cols',state.cols);$('board').replaceChildren();for(let r=0;r<state.rows;r++)for(let c=0;c<state.cols;c++){const b=document.createElement('button'),free=state.free&&state.freeAt[0]===r&&state.freeAt[1]===c,on=C.checked(state,r,c);b.className='cell'+(on?' checked':'')+(free?' free':'')+(winning.has(`${r},${c}`)?' winning':'');b.dataset.pos=`${r},${c}`;b.setAttribute('aria-label',`${r+1}行${c+1}列 ${free?'FREE':state.cells[r][c].text||'空欄'} ${on?'チェック済み':'未チェック'}`);if(!editing)b.setAttribute('aria-pressed',String(on));const mark=document.createElement('span');mark.className='mark';mark.textContent=on?'✓':`${r+1}·${c+1}`;const t=document.createElement('span');t.className='cell-text';t.textContent=free?'FREE':state.cells[r][c].text||(editing?'入力する':'');b.append(mark,t);b.addEventListener('click',()=>{if(editing){if(free){$('hint').textContent='FREEの文章を編集するには、FREEを無効にしてください。';return;}selected=[r,c];$('editor-title').textContent=`${r+1}行・${c+1}列を編集`;$('cell-text').value=state.cells[r][c].text;$('editor').showModal();$('cell-text').focus();}else if(!free){state.cells[r][c].checked=!state.cells[r][c].checked;save();render();document.querySelector(`[data-pos="${r},${c}"]`).focus({preventScroll:true});}});$('board').append(b);}
$('rules').textContent=state.rows===state.cols?'成立条件：縦・横・斜めの全マスをチェック':'成立条件：縦・横の全マスをチェック（長方形は斜め判定なし）';}
function resize(rows,cols){state.rows=rows;state.cols=cols;if(state.freeAt[0]>=rows||state.freeAt[1]>=cols)state.freeAt=[Math.floor(rows/2),Math.floor(cols/2)];save();render();}
$('rows').onchange=e=>resize(Number(e.target.value),state.cols);$('cols').onchange=e=>resize(state.rows,Number(e.target.value));document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>resize(Number(b.dataset.size),Number(b.dataset.size)));
$('title').oninput=e=>{state.title=e.target.value;$('card-title').textContent=state.title||'マイビンゴ';save();};for(const mode of ['edit','play'])$(mode).onclick=()=>{state.mode=mode;save();render();};
$('free').onchange=e=>{state.free=e.target.checked;if(state.free&&(state.freeAt[0]>=state.rows||state.freeAt[1]>=state.cols))state.freeAt=[Math.floor(state.rows/2),Math.floor(state.cols/2)];save();render();};$('free-position').onchange=e=>{state.freeAt=e.target.value.split(',').map(Number);save();render();};
$('editor').addEventListener('close',()=>{if($('editor').returnValue==='save'&&selected){const[r,c]=selected;state.cells[r][c].text=$('cell-text').value;save();render();}if(selected)document.querySelector(`[data-pos="${selected.join(',')}"]`)?.focus({preventScroll:true});selected=null;});
$('clear').onclick=()=>{if(!confirm('すべてのチェックを解除しますか？ 隠れたマスも解除されます。FREEはそのままです。'))return;state.cells.flat().forEach(c=>c.checked=false);save();render();};$('reset').onclick=()=>{if(!confirm('カード名・文章・チェックをすべて削除し、5×5に戻しますか？ この操作は取り消せません。'))return;state=C.create();save(true);render();};$('save').onclick=()=>{if(storageBlocked&&!confirm('現在のカードで保存データを上書きしますか？'))return;save(true);};render();
